config/routes.rb
Rails.application.routes.draw do
  root to: "admin/admin#index"
  namespace :admin do
    devise_for :users, controllers: {
        sessions: 'admin/sessions'
      }
    resources :users
    resources :addresses do
      collection do
        get :find_external_address
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :addresses, :only => [:index]
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates_presence_of :zip_code, :street, :state, :city, :neighborhood
  validates_uniqueness_of :zip_code
  validates :zip_code, length: { minimum: 8, maximum: 8 }

  scope :by_zip_code, ->(zip_code) { where(zip_code: zip_code) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates_presence_of :name, :email

end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < Admin::AdminController

  def index
    @addresses = InternalZipCodeSearcher.new(params_zip_code).get_address
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(params_address)

    if @address.save
      flash[:notice] = "Criado com sucesso"
      redirect_to admin_addresses_path
    else
      flash[:error] = @address.errors.full_messages
      render action: :new
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:notice] = "Excluído com sucesso"
    redirect_to admin_addresses_path
  end

  def update
    @address = Address.find(params[:id])

    if @address.update_attributes(params_address)
      flash[:notice] = "Atualizado com sucesso"
      redirect_to admin_addresses_path
    else
      flash[:error] = @address.errors.full_messages
      render action: :edit
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def find_external_address
    zip_code_searcher = ExternalZipCodeSearcher.new(params_zip_code)

    if zip_code_searcher.valid?
      render json: zip_code_searcher.get_address
    else
      render json: {}
    end
  end

  private

  def params_address
    params.require(:address).permit(:zip_code, :state, :city, :neighborhood, :street)
  end

  def params_zip_code
    params.permit(:zip_code)[:zip_code]
  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_admin_user!

  layout "admin"

end

app/controllers/admin/confirmations_controller.rb
class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  before_filter :configure_sign_in_params, only: [:create]

  layout "sessions"

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end

  protected
  
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in)
  end
end

app/controllers/admin/unlocks_controller.rb
class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)

    if @user.save
      flash[:notice] = "Criado com sucesso"
      redirect_to admin_users_path
    else
      flash[:error] = @user.errors.full_messages
      render action: :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Excluído com sucesso"
    redirect_to admin_users_path
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params_user)
      flash[:notice] = "Atualizado com sucesso"
      redirect_to admin_users_path
    else
      flash[:error] = @user.errors.full_messages
      render action: :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  private

  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base

  protect_from_forgery with: :null_session
  before_action :authenticate

  private

  def authenticate
    authenticate_or_request_with_http_token do |token, options|
      token == YAML.load_file('config/secrets.yml')[Rails.env]["secret_key_base"]
    end
  end

end

app/controllers/api/v1/addresses_controller.rb
class Api::V1::AddressesController < Api::ApiController

  def index
    address = InternalZipCodeSearcher.new(params_zip_code).get_address

    if address.present?
      render json: address.to_json
    else
      render json: { text: "not found" }, status: 404
    end
  end

  private

  def params_zip_code
    params.require(:address).permit(:zip_code)[:zip_code]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def message_kind(name)
    if name == :error
      "alert-danger"
    else
      "alert-success"
    end
  end

  def method_name
    
  end
end

app/views/admin/addresses/_form.haml
.panel.panel-default
  .panel-heading
    Cadastro: Código de Endereçamento Postal - CEP
  .panel-body
    = form_for([:admin, @address]) do |f|
      .form-group
        = f.label :zip_code
        = f.text_field :zip_code, class: "form-control input-large"
      .form-group
        = f.label :state
        = f.text_field :state, class: "form-control input-large"
      .form-group
        = f.label :city
        = f.text_field :city, class: "form-control input-large"
      .form-group
        = f.label :neighborhood
        = f.text_field :neighborhood, class: "form-control input-large"
      .form-group
        = f.label :street
        = f.text_field :street, class: "form-control input-large"
      = f.submit "Salvar", class: "btn btn-primary"
        
:javascript
  $("#address_zip_code").blur(function(){
    $.get("/admin/addresses/find_external_address?zip_code=" + $("#address_zip_code").val(), function(data){
      $("#address_state").val(data["state"]);
      $("#address_street").val(data["address"]);
      $("#address_city").val(data["city"]);
      $("#address_neighborhood").val(data["neighborhood"]);
    });
  });

app/views/admin/addresses/index.haml
.panel.panel-default
  .panel-heading
    Código de Endereçamento Postal - CEP
  .panel-body
    = form_tag(admin_addresses_path, method: "get", class: "navbar-form navbar-left") do
      .form-group
        = text_field_tag "zip_code", params[:zip_code], class: "form-control", placeholder: "Buscar por CEP"
        = submit_tag "Buscar", class: "btn btn-default"
        = link_to "Adicionar", new_admin_address_path, role: "button", class: "btn btn-success btn-large"
  %table.table
    %thead
      %tr
        %th CEP
        %th Estado
        %th Cidade
        %th Bairro
        %th Rua
        %th Ações
    %tbody
      - @addresses.each do |address|
        %tr
          %td= address.zip_code
          %td= address.state
          %td= address.city
          %td= address.neighborhood
          %td= address.street
          %td
            = button_to 'Excluir', { action: :destroy, id: address.id }, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-link btn-danger"
            %button.btn.btn-link.btn-success= link_to 'Editar', edit_admin_address_path(address)

app/views/admin/users/_form.haml
.panel.panel-default
  .panel-heading
    Cadastro: Usuários
  .panel-body
    = form_for([:admin, @user]) do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control input-large"
      .form-group
        = f.label :email
        = f.text_field :email, class: "form-control input-large"
      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control input-large"
      .form-group
        = f.label :password_confirm
        = f.password_field :password_confirmation, autocomplete: "off", class: "form-control input-large"
      = f.submit "Salvar", class: "btn btn-primary"

app/views/admin/users/edit.haml
= render "form"

app/views/admin/users/index.haml
.panel.panel-default
  .panel-heading
    Usuários
  .panel-body
    = link_to "Adicionar", new_admin_user_path, role: "button", class: "btn btn-success btn-large"
  %table.table
    %thead
      %tr
        %th Nome
        %th Email
        %th Ações
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td
            = button_to 'Excluir', { action: :destroy, id: user.id }, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-link btn-danger"
            %button.btn.btn-link.btn-success= link_to 'Editar', edit_admin_user_path(user)

app/views/admin/users/new.haml
= render "form"

app/views/admin/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_flash_messages.haml
- flash.each do |name, message|
  .alert{class: message_kind(name)}= message

app/views/layouts/admin.haml
!!! 5
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => I18n.locale, :lang => I18n.locale}
  %head
    %title Goku E-Commerce
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "layouts/admin/navbar"
    = render "layouts/flash_messages"
    .container-fluid
      .row
        %div{ class: "col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" }
        = yield

app/views/layouts/admin/_navbar.haml
%nav{class: "navbar navbar-inverse navbar-fixed-top", style: "position: relative !important"}
  .container-fluid
    .navbar-header
      = link_to "Goku E-Commerce", root_path, class: "navbar-brand"
    .btn-group
      %button{ class: "btn btn-default dropdown-toggle navbar-btn", "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false }
        Cadstro
      %ul.dropdown-menu
        %li= link_to "Usuários", admin_users_path
        %li= link_to "Código de Endereçamento Postal", admin_addresses_path
    .btn-group.navbar-right
      %button{ class: "btn btn-default dropdown-toggle navbar-btn", "data-toggle": "dropdown", "aria-haspopup": true, "aria-expanded": false }
        = current_admin_user.name
      %ul.dropdown-menu
        %li= link_to "Sair", destroy_admin_user_session_path

app/views/layouts/application.haml
%html
%head
  %title
    GokuEcommerce
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  = yield

app/views/layouts/sessions.haml
!!! 5
%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => I18n.locale, :lang => I18n.locale}
  %head
    %title Goku E-Commerce
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    :css
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        height: auto;
        margin-bottom: 15px;
        margin-top:15px;
      }
%body
  .container
    = yield